import type { Metadata } from "next";
import "./globals.css";
import Header from "@/src/common/header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header></Header>
        <main className="bg-[url('/bg.jpg')]">{children}</main>
      </body>
    </html>
  );
}
